[project]
authors = ["David Freitag <david@freitag.site>"]
channels = ["conda-forge"]
name = "frontend-vite"
platforms = ["win-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=22.13.0,<22.14"
